spring:
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    properties:
      group.id: arantes
    consumer:
      properties:
        retry:
          backoff:
            ms: 1000 # Intervalo de retry (em milissegundos)
      max-poll-records: 1 # Número máximo de registros por poll (consulta)
      enable-auto-commit: false # Desabilitar commit automático do offset
    listener:
      concurrency: 3 # Número de threads de consumidores simultâneos
      ack-mode: manual # Modo de acknowledgment manual
      max-attempts: 5 # Número máximo de tentativas automáticas
